# version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=licit_user
      - POSTGRES_PASSWORD=licit_password
      - POSTGRES_DB=licit_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: